version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/deploy_laravel.sh
      timeout: 300
      runas: root
    - location: script/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 120
      runas: root    
  
